### PR TITLE
refined project token

### PR DESCRIPTION
**Pull request by braver**
Replaces #413 and solves its merge conflicts and lint errors.

### CODE REVIEW

**Comment by jrappen** [comment]
@braver, @groteworld:

This PR broke SL for me:


```text
Traceback (most recent call last):
  File "...\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "...\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "...\SublimeLinter\sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "...\SublimeLinter\lint\linter.py", line 924, in lint_view
    view_settings = linter.get_view_settings(inline=False)
  File "./python3.3/functools.py", line 251, in wrapper
  File "...\SublimeLinter\lint\linter.py", line 449, in get_view_settings
    settings = self.get_merged_settings()
  File "...\SublimeLinter\lint\linter.py", line 496, in get_merged_settings
    self.replace_settings_tokens(settings)
  File "...\SublimeLinter\lint\linter.py", line 594, in replace_settings_tokens
    if folder['path'] in view.file_name():
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by braver** [comment]
Are you sure it's specifically this change, or it is a particular version of SL you're having problems with? If you have more info, could you open an issue for this?

**Comment by jrappen** [comment]
If you look at the log, the last error specifically points at the changes made in this PR. Will open an issue.

**Comment by jrappen** [comment]
moved to #641

**Pull request merged**
