### PR TITLE
Override can_lint for NodeLinter

### PR DESCRIPTION
**Pull request by tschaub**
Without this change, if the linter executable is not found on the path (with [`util.which(cmd)`](https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/linter.py#L1443-L1457)), the NodeLinter will be disabled.  Since `can_lint` is called with the view syntax only (and not the view), and the executable used will vary based on the view filename, the `NodeLinter`'s implementation is optimistic, determining its ability to lint based on syntax alone.

It seems to me like the only alternative would be to call `can_lint` with the `view` as well - but this would diminish the effect of caching the result.

Without `eslint` installed globally, I was unable to get the [SublimeLinter-contrib-eslint](https://github.com/roadhump/SublimeLinter-eslint) plugin working after inheriting from `NodeLinter`.  With the changes in this branch, the `eslint` plugin works with a local install (and [this change](https://github.com/tschaub/SublimeLinter-eslint/compare/node-linter) to inherit from `NodeLinter`).

### CODE REVIEW

**Comment by skj3gg** [comment]
I'll test this out tonight. What OS/shells has this been tried with. Thanks!

Also discussed in #157

**Comment by tschaub** [comment]
Tested on OSX with bash (though this should have no impact).  As mentioned above, this is an "optimistic" way to determine if the linter can lint the given syntax - based on the linter's configured syntax alone.  This makes no change to the way the executable binary is looked up when `lint` is actually run.

Let me know if you have any suggestions on alternative ways to handle this.  I'm happy to rework this branch.

**Comment by tschaub** [comment]
It's worth adding that to test this, I checked out https://github.com/tschaub/SublimeLinter3/commit/5dcefe93c7b4d7fa5b4881974f77ddf209fc7af3 and https://github.com/tschaub/SublimeLinter-eslint/tree/node-linter as packages.  I do not have `eslint` on my path, but I have it installed locally for several projects.  When opening files in a project with `eslint` installed locally, I confirmed that the linter was running as expected.

**Comment by malandrew** [comment]
I will test this out tomorrow.

**Comment by tschaub** [comment]
@malandrew or @skj3gg - any chance you've taken a look at this?  I'd be happy to talk over or work on alternatives.  I'm looking forward to using locally installed node linters.

**Comment by skj3gg** [comment]
Thanks, sorry, had to get a Windows VM and going.

**Comment by tschaub** [comment]
Thanks for merging @skj3gg.  I look forward to the next release.

**Comment by skj3gg** [comment]
It actually should be out in the wild currently, so you should be able to use it.

**Pull request merged**
