### PR TITLE
ComposerLinter submodule

### PR DESCRIPTION
**Pull request by cjquinn**
See #522

### CODE REVIEW

**Comment by ajmichels** [comment]
It would be great if you could add some more context to your commit messages. Yes we have context in the issue but that doesn't actually live with the code in the same way that commit messages do. The issue is part of GitHub not the repo itself.

**Comment by ajmichels** [comment]
To expand on my previous comment. Your code is hopefully self evident and has comments where needed to cover the "what" of your changes. Your commits automatically cover the "who" and "when". The commit _messages_ and pull request should cover the "why" of the changes. Why were the changes necessary? Why/how do they improve the code? Why were they made now rather than before or at a later time? You don't have to literally answer these questions but this is the kind of stuff that makes up a good commit message and provides value to any developer that comes after you.

**Comment by cjquinn** [comment]
No I understand, I'll add some more context to the above commits.

**Comment by ajmichels** [comment]
Also your commit 21ad18e should be squashed into a previous commit, whichever one introduced the typo. If you were fixing a typo that has been in the code for a long time and was not part of your changes it would be a valuable commit. But since you introduced the typo yourself in a commit that is part of this PR it doesn't really do anything except to highlight your mistake.

**Comment by cjquinn** [comment]
Updated and squashed commit messages - you'll have to bear with me I'm pretty use to my one man repos!

**Comment by kohenkatz** [comment]
I hope this gets in soon so I can do a linter for [Psalm](https://getpsalm.org/) which *cannot* currently be installed globally - it must be installed using Composer in order to work.

**Comment by braver** [comment]
@groteworld @jawshooah the guy went through all this effort, responded to feedback in a timely manner, even cleaned up his commit messages... You can’t leave him hanging like this!

**Comment by groteworld** [comment]
This is missing:
1. changes to `create_linter_info.json` adding the ComposerLinter
1. Documentation for Composer Linter
1. adding it to ignore list in `lint/linter.py

Since this has been waiting a while. I'll do 1 and 3 for you, but it would be helpful if someone with knowledge of it could do the documentation page

**Comment by groteworld** [comment]
nvm looks like 3 was done, and 1 has now been done. should be in next release. ETA 2 days

My apologies for the slow response time and thank you everyone for your work!

**Pull request merged**
