### PR TITLE
Inline tooltip [updated]

### PR DESCRIPTION
**Pull request by TheKevJames**
Copied from #510, see original discussion there.

### CODE REVIEW

**Comment by TheKevJames** [comment]
Ah, my bad, didn't notice the codecov callback.

@groteworld it looks like we don't have much in the way of scaffolding for tests on mini-features like this one. How would you like me to proceed on building those?

**Comment by groteworld** [comment]
No that's fine. It's more a work in progress to get tests in. I'll try to review this soon

**Comment by outpunk** [comment]
@groteworld Any updates? Pleeeeeeease =)

**Comment by pablo-coco** [comment]
there is a curse on this issue

**Comment by TheKevJames** [comment]
@groteworld Any chance you have a rough estimate on when you'll find the time to look at this?

**Comment by averypfeiffer** [comment]
@TheKevJames I know this may be an unpopular opinion. But I switched to VSCode from Sublime specifically because of this issue. They have a very nice implementation of tooltips over there, I haven't looked back since the switch. 

Just thought I'd mention it as a possible alternative.

**Comment by TheKevJames** [comment]
You switched editors because one of the plugins for that editor has not yet merged an inline tooltip PR,? Seems like overkill to me. On a personal level, I've found VSCode (and Atom) to be noticeably slower than Sublime -- as a bunch of [benchmarks](https://blog.xinhong.me/post/sublime-text-vs-vscode-vs-atom-performance-dec-2016/) have found. I think I'll stick with Sublime.

Y'all know you can [install from source](http://www.sublimelinter.com/en/latest/installation.html#installing-from-source) literally just by checking out this branch into a folder, right?

**Comment by groteworld** [comment]
Extremely sorry everyone, I know it can be frustrating to have this be so close yet so far. I've been speaking at a conference the last week so I've been extremely absent in everything but that. I'm traveling back today, and will try to look at it a little. at the very least I will review tomorrow. I Promise!

I have been having some roll out thoughts, and may create a config variable to turn this off, that will be set to false at default until a later release. Similar to a deprecation schedule, except the reverse. I feel this is the least disruptive to the current users, but informs them that this new feature is out. This will also give us some time to iron out issues before a huge release like this.

**Comment by Kristinita** [comment]
@TheKevJames , @groteworld , please, look **#563**.

Thanks.

**Pull request merged**
