### PR TITLE
Allow relative paths in settings

### PR DESCRIPTION
**Pull request by inkhsutesou**
Creates an absolute path from the stringed path passed into linter.py

### CODE REVIEW

**Comment by grotewold** [comment]
I have a couple other commits to add and then I'll push this in the next release. Thanks!

**Comment by grotewold** [comment]
Added with v3.6.0

**Comment by NotSqrt** [comment]
This broke SublimeLinter : 
```
  File "/home/user/.config/sublime-text-3/Packages/SublimeLinter/lint/linter.py", line 1169, in build_cmd
    cmd[0:1] = util.convert_type(os.path.abspath(path), [])
  File "./posixpath.py", line 379, in abspath
  File "./posixpath.py", line 64, in isabs
AttributeError: 'tuple' object has no attribute 'startswith'
```

**Comment by NotSqrt** [comment]
At that moment, path can be equal to :
``('/usr/bin/python3', '/usr/local/bin/flake8')`` 
or ``('/usr/bin/python3', '/usr/local/bin/pylint')``

**Pull request merged**
