### PR TITLE
Fix build by ignoring imperative mood docstrings.

### PR DESCRIPTION
**Pull request by veelo**
Alternative to #583.

### CODE REVIEW

**Comment by braver** [comment]
@groteworld builds are failing, which isn't really inviting for contributors. This solution seems preferable over #583, and just merging this seems a lot less work than fixing all the comments. We could do that at some point, but I think the primary concern should be to keep people on board and contributing improvements.

**Comment by groteworld** [comment]
These docs have been updated in favor of ignoring. Thank you for your contribution though!!

**Comment by veelo** [comment]
Can you restart Travis on PRs with failing builds manually, or do we have to make a phony commit to trigger a rebuild?

**Comment by groteworld** [comment]
I believe I can either restart the builds but if not i will manually run through the build. I'll look into that now. Thanks again!

**Pull request closed without merging**
